language: java
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: true
    
script:
  - ./gradlew -s -Dorg.gradle.daemon=false clean build mockTest publishToMavenLocal

after_script:
  - bash <(curl -s https://codecov.io/bash)
  
