language: java
jdk: openjdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - docker

before_install:
  - docker build -t jenkins-rest/jenkins src/main/docker
  - docker run -d --rm -p 8080:8080 --name jenkins-rest jenkins-rest/jenkins

install: true
    
script:
  - ./gradlew -s -Dorg.gradle.daemon=false clean build mockTest publishToMavenLocal integTest

after_script:
  - docker stop jenkins-rest
  - bash <(curl -s https://codecov.io/bash)
